import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F9FAFB',
  },
  screen: {
    flex: 1,
    paddingTop: 40,
    paddingHorizontal: 20,
    paddingBottom: 20,
    backgroundColor: '#F9FAFB',
  },
  formContainer: {
    padding: 20,
    backgroundColor: '#F9FAFB',
  },
  title: {
    fontSize: 26,
    fontWeight: '600',
    marginBottom: 16,
    color: '#111827',
  },
  subtitle: {
    fontSize: 16,
    color: '#6B7280',
    marginBottom: 24,
  },
  label: {
    fontSize: 14,
    color: '#374151',
    marginBottom: 4,
    marginTop: 12,
  },
  input: {
    borderWidth: 1,
    borderColor: '#D1D5DB',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: '#FFFFFF',
    fontSize: 14,
  },
  multilineInput: {
    minHeight: 120,
  },
  primaryButton: {
    backgroundColor: '#2563EB',
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 999,
    alignItems: 'center',
    marginBottom: 16,
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '600',
  },
  secondaryButton: {
    flex: 1,
    backgroundColor: '#E5E7EB',
    paddingVertical: 12,
    marginHorizontal: 4,
    borderRadius: 999,
    alignItems: 'center',
  },
  secondaryButtonText: {
    color: '#111827',
    fontSize: 14,
    fontWeight: '500',
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  textButton: {
    marginTop: 16,
    alignItems: 'center',
  },
  textButtonText: {
    color: '#2563EB',
    fontSize: 14,
    fontWeight: '500',
  },
  listItem: {
    backgroundColor: '#FFFFFF',
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 12,
    marginBottom: 10,
  },
  listItemTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#111827',
  },
  listItemSubtitle: {
    marginTop: 4,
    fontSize: 13,
    color: '#6B7280',
  },
  emptyText: {
    marginTop: 16,
    fontSize: 14,
    color: '#6B7280',
  },
  flex: {
    flex: 1,
  },
  smallButton: {
    marginLeft: 8,
    backgroundColor: '#111827',
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
  },
  smallButtonText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '500',
  },
  chipContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 8,
  },
  chip: {
    backgroundColor: '#DBEAFE',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    marginRight: 6,
    marginBottom: 6,
  },
  chipText: {
    fontSize: 12,
    color: '#1D4ED8',
  },
  photoPreviewContainer: {
    marginTop: 8,
    marginBottom: 12,
  },
  photoPreview: {
    width: 80,
    height: 80,
    borderRadius: 8,
    marginRight: 8,
    backgroundColor: '#E5E7EB',
  },
  dangerButton: {
    marginTop: 8,
    paddingVertical: 12,
    borderRadius: 999,
    alignItems: 'center',
    backgroundColor: '#DC2626',
  },
  dangerButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
  searchResults: {
    marginTop: 12,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    marginTop: 12,
    marginBottom: 8,
    color: '#111827',
  },
  countryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  countryFlag: {
    fontSize: 20,
    marginRight: 6,
  },
  countryNameText: {
    fontSize: 14,
    color: '#111827',
    fontWeight: '500',
  },
  countryHero: {
    alignItems: 'center',
    marginBottom: 8,
  },
  countryHeroFlag: {
    fontSize: 40,
  },
  homeRoot: {
    flex: 1,
    backgroundColor: '#F9FAFB',
  },
  homeScrollContent: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 96,
  },
  homeTopBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 12,
    marginTop: 32,
    marginBottom: 8,
    backgroundColor: '#FFFFFF',
  },
  homeTopBrand: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  homeTopBrandLogo: {
    width: 28,
    height: 28,
    borderRadius: 999,
    backgroundColor: '#F97316',
    marginRight: 8,
  },
  homeTopBrandText: {
    fontSize: 20,
    fontWeight: '700',
    color: '#111827',
  },
  homeTopActions: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  homeTopIconButton: {
    marginLeft: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: '#F3F4F6',
    flexDirection: 'row',
    alignItems: 'center',
  },
  homeTopIconText: {
    fontSize: 16,
  },
  homeTopIconBadge: {
    marginLeft: 4,
    fontSize: 11,
    fontWeight: '600',
    color: '#F97316',
  },
  homePromoCard: {
    flexDirection: 'row',
    backgroundColor: '#FEF3C7',
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
  },
  homePromoContent: {
    flex: 1,
    paddingRight: 8,
  },
  homePromoBadge: {
    alignSelf: 'flex-start',
    backgroundColor: '#F97316',
    color: '#FFFFFF',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
    fontSize: 11,
    fontWeight: '700',
    marginBottom: 8,
  },
  homePromoTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#111827',
    marginBottom: 4,
  },
  homePromoText: {
    fontSize: 13,
    color: '#4B5563',
    marginBottom: 8,
  },
  homePromoButton: {
    alignSelf: 'flex-start',
    backgroundColor: '#F97316',
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  homePromoButtonText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '600',
  },
  homePromoIllustration: {
    justifyContent: 'center',
    alignItems: 'center',
    width: 72,
  },
  homePromoEmoji: {
    fontSize: 32,
  },
  homePagerDots: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  homePagerDot: {
    width: 6,
    height: 6,
    borderRadius: 999,
    backgroundColor: '#E5E7EB',
    marginHorizontal: 3,
  },
  homePagerDotActive: {
    backgroundColor: '#F97316',
    width: 8,
    height: 8,
  },
  homeHero: {
    height: 260,
    borderRadius: 24,
    overflow: 'hidden',
    marginBottom: 16,
  },
  homeHeroImage: {
    width: '100%',
    height: '100%',
  },
  homeHeroOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    padding: 20,
    backgroundColor: 'rgba(15, 23, 42, 0.35)',
  },
  homeHeroTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#FFFFFF',
    marginBottom: 6,
  },
  homeHeroSubtitle: {
    fontSize: 13,
    color: '#E5E7EB',
    marginBottom: 12,
  },
  homeHeroButton: {
    alignSelf: 'flex-start',
    backgroundColor: '#F97316',
    borderRadius: 999,
    paddingHorizontal: 18,
    paddingVertical: 10,
  },
  homeHeroButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
  homeSection: {
    marginBottom: 24,
  },
  homeSectionTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#111827',
    marginBottom: 12,
  },
  homeSectionHorizontal: {
    marginBottom: 4,
  },
  homeGuideCard: {
    width: 260,
    marginRight: 12,
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    overflow: 'hidden',
  },
  homeGuideImage: {
    width: '100%',
    height: 140,
  },
  homeGuideMeta: {
    padding: 12,
  },
  homeGuideTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#111827',
  },
  homeGuideSubtitle: {
    marginTop: 4,
    fontSize: 13,
    color: '#6B7280',
  },
  homeGuideAuthorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
  },
  homeGuideAuthorAvatar: {
    width: 24,
    height: 24,
    borderRadius: 999,
    backgroundColor: '#F97316',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
  },
  homeGuideAuthorAvatarText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '600',
  },
  homeGuideAuthorText: {
    fontSize: 12,
    color: '#6B7280',
  },
  homeWeekendRow: {
    marginTop: 4,
  },
  homeWeekendCard: {
    width: 200,
    borderRadius: 16,
    overflow: 'hidden',
    backgroundColor: '#111827',
  },
  homeWeekendImage: {
    width: '100%',
    height: 150,
  },
  homeWeekendMeta: {
    position: 'absolute',
    left: 16,
    bottom: 16,
  },
  homeWeekendTitle: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
  },
  homePopularRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  homePopularChip: {
    backgroundColor: '#E5E7EB',
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
    marginRight: 8,
    marginBottom: 8,
  },
  homePopularChipText: {
    fontSize: 13,
    color: '#374151',
  },
  guidesBookContainer: {
    marginTop: 16,
    marginBottom: 24,
  },
  guidesBookTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#111827',
    textAlign: 'center',
    marginBottom: 16,
  },
  guidesBookInputLarge: {
    borderRadius: 12,
    backgroundColor: '#F3F4F6',
    paddingHorizontal: 14,
    paddingVertical: 10,
    marginBottom: 8,
  },
  guidesBookRow: {
    flexDirection: 'row',
    marginBottom: 12,
  },
  guidesBookInputSmall: {
    flex: 1,
    borderRadius: 12,
    backgroundColor: '#F3F4F6',
    paddingHorizontal: 14,
    paddingVertical: 10,
    marginRight: 8,
  },
  guidesBookInputLabel: {
    fontSize: 12,
    color: '#6B7280',
    marginBottom: 4,
  },
  guidesBookInputPlaceholder: {
    fontSize: 14,
    color: '#9CA3AF',
  },
  guidesBookInputValue: {
    fontSize: 14,
    color: '#111827',
  },
  guidesBookSearchButton: {
    alignSelf: 'center',
    marginTop: 4,
    marginBottom: 16,
    backgroundColor: '#F97316',
    borderRadius: 999,
    paddingHorizontal: 28,
    paddingVertical: 10,
  },
  guidesBookSearchButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '600',
  },
  guidesBookRecentSection: {
    marginTop: 4,
  },
  guidesBookRecentTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#111827',
    marginBottom: 8,
  },
  guidesBookRecentItem: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  guidesBookRecentIcon: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: '#111827',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  guidesBookRecentIconText: {
    color: '#FFFFFF',
    fontSize: 18,
  },
  guidesBookRecentTexts: {
    flex: 1,
  },
  guidesBookRecentPlace: {
    fontSize: 14,
    fontWeight: '600',
    color: '#111827',
  },
  guidesBookRecentMeta: {
    marginTop: 2,
    fontSize: 12,
    color: '#6B7280',
  },
  profileHeaderCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 16,
    marginBottom: 16,
  },
  profileHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  profileHeaderMain: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  profileAvatar: {
    width: 56,
    height: 56,
    borderRadius: 999,
    backgroundColor: '#111827',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  profileAvatarText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '700',
  },
  profileName: {
    fontSize: 18,
    fontWeight: '700',
    color: '#111827',
  },
  profileUsername: {
    marginTop: 2,
    fontSize: 13,
    color: '#6B7280',
  },
  profileHeaderActions: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  profileHeaderActionButton: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    paddingHorizontal: 14,
    paddingVertical: 6,
  },
  profileHeaderActionText: {
    fontSize: 13,
    fontWeight: '500',
    color: '#111827',
  },
  profileStatsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 16,
  },
  profileStat: {
    marginRight: 24,
  },
  profileStatNumber: {
    fontSize: 16,
    fontWeight: '700',
    color: '#111827',
  },
  profileStatLabel: {
    fontSize: 11,
    letterSpacing: 1.5,
    color: '#6B7280',
  },
  profileTabsRow: {
    flexDirection: 'row',
    marginTop: 12,
  },
  profileTab: {
    marginRight: 24,
    paddingBottom: 8,
  },
  profileTabLabel: {
    fontSize: 14,
    fontWeight: '500',
    color: '#6B7280',
  },
  profileTabLabelActive: {
    fontSize: 14,
    fontWeight: '600',
    color: '#F97316',
  },
  profileTabUnderline: {
    marginTop: 4,
    height: 2,
    borderRadius: 999,
    backgroundColor: '#F97316',
  },
  profileContent: {
    marginTop: 32,
    alignItems: 'center',
  },
  profileEmptyText: {
    fontSize: 14,
    color: '#6B7280',
    marginBottom: 16,
    textAlign: 'center',
  },
  profileEmptyButton: {
    backgroundColor: '#F97316',
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 999,
  },
  profileEmptyButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '600',
  },
  navBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    paddingHorizontal: 24,
    paddingTop: 8,
    paddingBottom: 12,
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
    backgroundColor: '#FFFFFF',
  },
  navItem: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  navItemActive: {
    borderRadius: 999,
    padding: 6,
    backgroundColor: '#F3F4F6',
  },
  navItemIcon: {
    fontSize: 20,
    color: '#4B5563',
  },
  navCenterButton: {
    width: 56,
    height: 56,
    borderRadius: 999,
    backgroundColor: '#F97316',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: -20,
    shadowColor: '#000000',
    shadowOpacity: 0.15,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  navCenterIcon: {
    fontSize: 28,
    color: '#FFFFFF',
    fontWeight: '700',
  },
});
